### ISSUE TITLE
Release Checklist + Automation Candidates 

### ISSUE THREAD

**Issue by davidbiancolin** [firesim/firesim#958]
The current tasks are still manual and are candidates for automation. Please add to this list as necessary.

Common:
- [ ] Update Changelog.
- [ ] Mint the release on Github.com using the Changelog 

For minor releases (1.Y) only:
- [ ] Create 1.Y.X branch, setup GH write protections 
- [ ] Update mergify backport rule
- [ ] Update GH Actions to run CI tasks on 

For patch releases (1.Y.X):
N/A

**Comment by davidbiancolin** [comment]
@davidbiancolin Update this based on the stable/latest discussion we had previously.
